### ISSUE TITLE
Inventory Tracking MVP

### ISSUE THREAD

**Issue by derektwest** [derektwest/Inventory-Recipes#1]
- [ ] Search through Inventory's "database" MVP
- [ ] Display inventory list based on days to expiration MVP
- [ ] Filter option: Meat/vegatable, or Asian/European recipes, etc.. SPRINKLES
